### ISSUE TITLE
Bug in virtualization of wait in LanguageVirtualization?

### ISSUE THREAD

**Issue by olafurpg** [scala-yinyang/scala-yinyang#42]
While trying to virtualize `wait(t, l)` in the following test (for directembedding)
```scala
  "dsl" should "work with a virtualized infix_wait(t, l)" in {
    runTest(
      dsl {
        "true" wait(1l)
      }) should be(Infix_WaitL(Const("true"), Const(1l)))
  }
```
I get the following NullPointerException
```
[error] /directembedding/tests/src/test/scala/ch/epfl/directembedding/test/LanguageVirtualizationSpec.scala:182: exception during macro expansion:
[error] java.lang.NullPointerException
[error] 	at ch.epfl.yinyang.transformers.LanguageVirtualization$VirtualizationTransformer.transform(LanguageVirtualization.scala:186)
[error] 	at ch.epfl.yinyang.transformers.LanguageVirtualization$VirtualizationTransformer.apply(LanguageVirtualization.scala:238)
[error] 	at ch.epfl.yinyang.transformers.LanguageVirtualization$VirtualizationTransformer$.apply(LanguageVirtualization.scala:78)
[error] 	at ch.epfl.directembedding.DETransformer$$anonfun$5.apply(DETransformer.scala:61)
[error] 	at ch.epfl.directembedding.DETransformer$$anonfun$5.apply(DETransformer.scala:61)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at ch.epfl.directembedding.DETransformer.apply(DETransformer.scala:68)
[error] 	at ch.epfl.directembedding.test.example.package$implementations$.liftRep(package.scala:119)
[error] 	at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:483)
[error] 	at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers$$anonfun$resolveJavaReflectionRuntime$2.apply(JavaReflectionRuntimes.scala:34)
[error] 	at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers$$anonfun$resolveJavaReflectionRuntime$2.apply(JavaReflectionRuntimes.scala:22)
[error] 	at scala.tools.nsc.typechecker.Macros$class.macroExpandWithRuntime(Macros.scala:751)
[error]       dsl {
[error]           ^
```
@vjovanov

**Comment by olafurpg** [comment]
The same happens for `infix_wait(t, t1, l)` with stack trace
```
[error] /directembedding/tests/src/test/scala/ch/epfl/directembedding/test/LanguageVirtualizationSpec.scala:190: exception during macro expansion:
[error] java.lang.NullPointerException
[error] 	at ch.epfl.yinyang.transformers.LanguageVirtualization$VirtualizationTransformer.transform(LanguageVirtualization.scala:190)
[error] 	at ch.epfl.yinyang.transformers.LanguageVirtualization$VirtualizationTransformer.apply(LanguageVirtualization.scala:238)
[error] 	at ch.epfl.yinyang.transformers.LanguageVirtualization$VirtualizationTransformer$.apply(LanguageVirtualization.scala:78)
[error] 	at ch.epfl.directembedding.DETransformer$$anonfun$5.apply(DETransformer.scala:61)
[error] 	at ch.epfl.directembedding.DETransformer$$anonfun$5.apply(DETransformer.scala:61)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error] 	at ch.epfl.directembedding.DETransformer.apply(DETransformer.scala:68)
[error] 	at ch.epfl.directembedding.test.example.package$implementations$.liftRep(package.scala:122)
[error] 	at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:483)
[error] 	at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers$$anonfun$resolveJavaReflectionRuntime$2.apply(JavaReflectionRuntimes.scala:34)
[error] 	at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers$$anonfun$resolveJavaReflectionRuntime$2.apply(JavaReflectionRuntimes.scala:22)
[error] 	at scala.tools.nsc.typechecker.Macros$class.macroExpandWithRuntime(Macros.scala:751)
[error]       dsl {
[error]           ^
```

**Comment by vjovanov** [comment]
Thanks for reporting I will fix this issue soon.
